version: '2'
services:
  web: 
    image: face-recog-server
    build: dockerfiles/face-recog-server
    links:
      - embedding-service
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/
      - ./tmp:/tmp/
      - ./store:/store/
      - ./svm-model:/svm-model/
      - /media/mike/HD/our_dataset_verification:/images/
      - /media/mike/HD/our_dataset_verification:/face-data
    environment:
      - "EMBEDDING_SERVER=embedding-service"
      - "EMBEDDING_PORT=5000"
  embedding-service: 
    image: embedding-service
    build: dockerfiles/embedding-service
    ports:
      - "5001:5000"
    container_name: embedding-service
    volumes:
      - ./src:/app/
      - ~/models/facenet/dl-20170511-185253/:/base-model/
