version: '2'
services:
  tracking:
    image: tracking-server
    build: dockerfiles/tracking-server
    links:
      - embedding-service
    ports:
      - "5002:5000"
    volumes:
      - ./src:/app/
      - ./tmp:/tmp/
    environment:
      - "EMBEDDING_SERVER=embedding-service"
      - "EMBEDDING_PORT=5000"
      - "PYTHONPATH=/app"
  embedding-service:
    image: embedding-service
    build: dockerfiles/embedding-service
    ports:
      - "5001:5000"
    container_name: embedding-service
    volumes:
      - ./src:/app/
      - ~/models/facenet/dl-20170511-185253/:/base-model/
