version: '2'
services:
  web: 
    image: face-recog-server
    build: dockerfiles/face-recog-server
    links:
      - embedding-service
    ports:
      - 5000:5000
    volumes:
      - ./src:/app/
      - ./tmp:/tmp/
      - ./store:/store/
      - ./svm-model:/svm-model/
      - ~/our_dataset:/images/ 
      - ~/our_dataset:/face-data 
  embedding-service: 
    image: embedding-service
    build: dockerfiles/embedding-service
    container_name: embedding-service
    volumes:
      - ./src:/app/
      - ~/models/facenet/dl-20170511-185253/:/base-model/
